### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by gregoryagu** [Thanood/aurelia-tree-view#3]
I am looking for a treeview that works well with Aurelia and would like to try this one.

However, I am having difficulty getting started.

It looks like it is meant to be installed as a plug in.  Is there a jspm install for it?

I tried jspm install npm:aurelia-tree-view but it was not found.

**Comment by gregoryagu** [comment]
I was able to install with this:  jsmp install github:Thanood/aurelia-tree-view 

The only thing I had to change was the mapping in config.js - 
from: "Thanod/aurelia-tree-view": "github:Thanood/aurelia-tree-view@master",
to "aurelia-tree-view": "github:Thanood/aurelia-tree-view@master"

Look very interesting!

**Comment by gregoryagu** [comment]
I got the sample up and running. For anyone else trying to get it running:
1. jspm install GitHub:Thanood/Aurelia-tree-view from the samples directory.
2. Update the mapping in config.js as noted above.
3. Run the app, it should fire up.  Click on the Components tab to see the many different samples.

Very nice work. I will definitely use this.

**Comment by Thanood** [comment]
Ah yes, there is no documentation yet as I created the project primarily as a test repo. But that "evolved" already as I'm using it at work so I might as well create the documentation app and upload it on github pages.

**Comment by Thanood** [comment]
The following steps should be sufficient, though:
- `npm install && jspm install` in root
- `jspm install` in sample directory
- `gulp watch` in root or sample directory

The sample loads the plugin here: https://github.com/Thanood/aurelia-tree-view/blob/master/sample/index.html#L23-L35

In your own app this would be the jspm command:
`jspm install aurelia-tree-view=github:Thanood/aurelia-tree-view`

It creates the mapping you mentioned. 😃 

Added this to the readme.

**Comment by gregoryagu** [comment]
Excellent
