### ISSUE TITLE
Modifying files

### ISSUE THREAD

**Issue by gregoryagu** [Thanood/aurelia-tree-view#4]
I want to clone your project to make a few minor changes.  I have cloned it to my github account, and then cloned it to my local machine so I can make changes.

My question is this: What do you use to compile?  I am using Visual Studio.  But I don't see how you compile the source to  amd, commonjs etc.  I typically write JS in Typescript, and then compile to AMD.

I have a lot of experience in Visual Studio and Team Foundation Services, but very little in GitHub and am trying to get up to speed.

**Comment by Thanood** [comment]
I'm using gulp.
- `gulp watch` - reloads the sample on every change
- `gulp build` - just builds the targets
- `gulp build-release` - does the same but to a folder called "dist" which is also on GitHub. This is the folder where jspm gets the GitHub version from.

Gulp is using Babel to transpile.
For more info on how this works I suggest having a look in the `build/tasks` directory. 😃

**Comment by gregoryagu** [comment]
Ah, thank you.
